apiVersion: v1
kind: Pod
metadata:
  name: quarkus-dev-ssh
  namespace: %s
  labels:
    app.kubernetes.io/name: quarkus-dev-ssh
spec:
  containers:
  - name: quarkus-dev-ssh
    image: %s
    env:
    - name: PASSWORD_ACCESS
      value: true
    - name: USER_NAME
      value: %s
    - name: USER_PASSWORD
      value: %s
    - name: DOCKER_MODS
      value: linuxserver/mods:openssh-server-ssh-tunnel
  automountServiceAccountToken: false