apiVersion: v1
kind: Service
metadata:
  name: %s
  namespace: %s
  labels:
    com.ise112.quarkus.k8s: reverseproxy
spec:
  selector:
    app: quarkus-dev-ssh
  ports:
  - port: %d
    protocol: TCP
    targetPort: %d
